#!/usr/bin/env python

import pathlib
import os
import json

import httpx


def generate(
    name, url="http://localhost:9000/openapi.json", config="client-generator.yml"
):
    print("Banchi Client Generator")

    os.system(f'openapi-python-client generate --url {url} --overwrite --config {config}')

if __name__ == "__main__":
    generate(
        "banchi",
        "http://localhost:9000/openapi.json",
        "config/banchi-client-generator.yml",
    )
