#!/bin/sh -e
export APP_ENV=dev
# uvicorn --proxy-headers banchiapi:get_application --factory --host 0.0.0.0 --reload --reload-dir ./banchiapi
LOGGING_LEVEL=10 APP_ENV=dev poetry run fastapi dev banchi/cmd/api.py --host 0.0.0.0 --port 9000
