#!/bin/sh -e
export APP_ENV=dev
# uvicorn --proxy-headers banchiapi:get_application --factory --host 0.0.0.0 --reload --reload-dir ./banchiapi
poetry run uvicorn --proxy-headers banchi.api:get_application --factory --host 0.0.0.0 --reload
